sudo: required

language: generic

services:
  - docker

before_install:
  - echo "image create"
  - docker build -t jms0324/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jms0324/docker-react-app npm run test -- --coverage

# after_success:
#   - echo "success"

deploy: 
  provider: elsticbeanstalk
  region: "ap-northeast-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-250058502806"
  bucket_paht: "react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY