sudo: required

language: generic

services:
  - docker

before_install:
  - echo "image create"
  - docker build -t jms0324/docker-react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true jms0324/docker-react-app npm run test -- --coverage

after_success:
  - echo "success"